language: node_js
node_js:
  - 16.13.1
cache: 
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test
  - npm start

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: main